import { createDocumentHandler } from '@/lib/artifacts/server';
import { JSONValue } from 'ai';

export const researchUpdateDocumentHandler =
	createDocumentHandler<'research_update'>({
		kind: 'research_update',
		onCreateDocument: async ({ title, dataStream }) => {
			// Research updates are generated by the workflow, so we just return an empty content
			return '';
		},
		onUpdateDocument: async ({ document, description, dataStream }) => {
			// Research updates are generated by the workflow, so we just return the existing content
			return document.content || '';
		},
	});
